# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yikes!
email: seventy6.com@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Keep your mind focused on one task across every screen you own.
baseurl: "/yikes-landingpage/" # the subpath of your site, e.g. /blog
url: "https://seventy6.github.io/" # the base hostname & protocol for your site
twitter_username: nickwforsberg
github_username:  seventy6

# Build settings
markdown: kramdown
